name = "gleshell"
version = "0.1.0"
description = "A structured-data shell in Gleam, inspired by Nushell"
licences = ["Apache-2.0"]

[dependencies]
gleam_stdlib = ">= 1.0.3 and < 2.0.0"
argv = ">= 1.1.0 and < 2.0.0"
simplifile = ">= 2.6.0 and < 3.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
filepath = ">= 1.1.2 and < 2.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
